Add support for the include directive in XCompose files
ibus/ibus pull request #2296
Opened 2021-01-24 15:37 UTC by lf-

We also fix an issue with excess space at the start of lines stopping
comments being recognized.

2021-02-02 02:54 UTC, fujiwarat requested changes

2021-02-16 04:27 UTC, fujiwarat commented
@lf- Do you have a chance to update the patch?

2021-02-16 04:34 UTC, lf- commented
@fujiwarat Yes, I plan to work on the patch this week during my reading break. Sorry I took a while to get to it, school has been very difficult.

2021-02-18 07:39 UTC, lf- commented on src/ibuscomposetable.c
> +                o = out + g_strlcat(out, getenv("HOME"), PATHLEN_MAX);
I think it is correct as it originally was: [`g_strlcat`](https://developer.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-strlcat) returns the length of the concatenated string or if it ran out of space, the max length - 1. Thus we want to add the value returned to the pointer to the start of the string so `o` becomes a pointer to the character we want to write next.

2021-02-18 08:16 UTC, lf- commented
OK I believe I've addressed all the feedback. I've force pushed the changed version.

2021-06-18 06:41 UTC, fujiwarat commented
Thank you for the patch.
I added another patch not to include the same compose file and the system EN compose file.

2021-06-18 06:41 UTC, closed without merging

2021-06-18 06:44 UTC, fujiwarat reviewed
Done