Fix unref problems with floating references
ibus/ibus pull request #2359
Opened 2021-10-14 07:32 UTC by ermshiperete

While trying to get a test client to work, I encountered some problems that this PR fixes. My test client uses `ibusimcontext.c` from the GTK client and the problems showed when I ran it with debug-enabled GLIB libraries.

When running with debug-enabled GLIB there are several critical errors output: "A floating object ... was finalized. This means
that someone called g_object_unref() on an object that had only a floating reference; the initial floating reference is not
owned by anyone and must be removed with g_object_ref_sink()."

This change fixes this by calling `g_object_ref_sink()` before `g_object_unref()` if we have a floating reference.

It also fixes another related problem where we called `g_object_unref()` on a static IBusText string (created with
`ibus_text_new_from_static_string()`) for which the API documentation says not to free.

2022-01-21 10:05 UTC, fujiwarat requested changes
Thank you very much for the patch.
If you wish your patch with the Git sign, please rebase the patch to the latest Git master updating my reviews.
Also please append a line "BUG=https://github.com/ibus/ibus/pull/2359" to your Git description .

Otherwise I can modify your patch.

2022-01-21 10:05 UTC, fujiwarat commented on src/ibusinputcontext.c
> +        }
Ditto.

2022-01-21 10:05 UTC, fujiwarat commented on src/ibusinputcontext.c
> +        }
Ditto.

2022-01-21 14:06 UTC, ermshiperete commented
I rebased and updated my PR.

2022-01-24 10:07 UTC, fujiwarat reviewed
Please put the capital word 'BUG' and full URL to follow other commits.

s|Bug=#2359|BUG=https://github.com/ibus/ibus/pull/2359|

2022-01-24 10:07 UTC, fujiwarat commented on src/ibusinputcontext.c
> +
I think the additional space is not needed too but it's not an important issue.

2022-01-24 10:46 UTC, ermshiperete commented
> Please put the capital word 'BUG' and full URL to follow other commits.
> 
> s|Bug=#2359|BUG=[https://github.com/ibus/ibus/pull/2359|](https://github.com/ibus/ibus/pull/2359%7C)

Ahh, sorry, I missed the fact that it's the full URL because I only looked at the commit message in GitHub :smile:

2022-01-25 12:24 UTC, merged

2022-03-07 17:16 UTC, bdaase commented
In case anyone comes a long here as well, this is supposed to fix https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5147

2022-03-29 15:23 UTC, hadess commented
> In case anyone comes a long here as well, this is supposed to fix https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5147

It is? Seems like it would cause those problems rather than fix them.

2022-03-29 15:27 UTC, bdaase commented
> It is? Seems like it would cause those problems rather than fix them.

This was expected to be the case in https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/5147#note_1398671 but turned out to not be the case.