configure: Use AC_C_BIGENDIAN macro to check endianness.
ibus/ibus pull request #2477
Opened 2023-02-22 18:16 UTC by tsutsui

`__BYTE_ORDER` is Linux specific (NetBSD has `_BYTE_ORDER`) but `AC_C_BIGENDIAN` seems enough.
https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/C-Compiler.html#index-AC_005fC_005fBIGENDIAN-1

2023-03-09 16:19 UTC, tsutsui commented
I notice there are extra `AC_MSG_CHECKING` and `AC_MSG_RESULT` messages so removed them in https://github.com/ibus/ibus/pull/2477/commits/f733c18e9aba35d51d9bf26c2e55b9feebd78c24.
```diff
--- configure.log.orig	2023-03-10 01:11:14.100489079 +0900
+++ configure.log	2023-03-10 01:10:19.408079100 +0900
@@ -207,8 +207,7 @@
 checking for sys/prctl.h... no
 checking for daemon... yes
 checking for dlclose in -lc... yes
-checking build system endianness... checking whether byte ordering is bigendian... no
-little
+checking whether byte ordering is bigendian... no
 checking for pkg-config... /usr/pkg/bin/pkg-config
 checking pkg-config is at least version 0.16... yes
 checking for GLIB... yes
```

2023-03-23 02:14 UTC, fujiwarat requested changes
Please delete the last period in the commit subject.
Also please append `BUG=https://github.com/ibus/ibus/pull/2477` in the commit description.

2023-03-25 19:40 UTC, tsutsui commented on configure.ac
>  AC_SUBST(ENDIAN)
> Please delete the last period in the commit subject. Also please append `BUG=https://github.com/ibus/ibus/pull/2477` in the commit description.

Well there is no way to predict a pull request number before commit.
Do you mean I should update the first commit and push my branch with `git push -f origin ac_c_bigendian` ?

2023-03-25 19:41 UTC, tsutsui commented
> Please delete the last period in the commit subject. Also please append `BUG=https://github.com/ibus/ibus/pull/2477` in the commit description.

Well there is no way to predict a pull request number before commit.
Do you mean I should update the first commit and push my branch with `git push -f origin ac_c_bigendian` ?

2023-03-25 19:43 UTC, tsutsui commented on configure.ac
>  AC_SUBST(ENDIAN)
> I think to append `ENDIAN="$ENDIAN ($ac_cv_c_bigendian, use ac_cv_c_bigendian to yes or no)"` next to `AC_SUBST(ENDIAN)` .

Sorry, I don't understand what the statement you suggested means.

2023-03-26 04:11 UTC, fujiwarat commented on configure.ac
>  AC_SUBST(ENDIAN)
The change will effect the configure result. E.g.
https://github.com/ibus/ibus/actions/runs/4376470045/jobs/7895795597?pr=2477#step:7:385

2023-03-26 04:15 UTC, fujiwarat commented
> Well there is no way to predict a pull request number before commit. Do you mean I should update the first commit and push my branch with `git push -f origin ac_c_bigendian` ?

Right, it helps me. I also will modify your patch if you're fine.

2023-03-26 05:00 UTC, tsutsui commented on configure.ac
>  AC_SUBST(ENDIAN)
> >  fi
> -AC_MSG_RESULT($ENDIAN)
>  AC_SUBST(ENDIAN)
> 
> The change will effect the configure result. E.g.
> https://github.com/ibus/ibus/actions/runs/4376470045/jobs/7895795597?pr=2477#step:7:385

Sorry I committed multiple revisions and github UI doesn't quote commentted lines exactly.
Which reivision/line is 'the change' you mean?

If you meant `AC_MSG_RESULT($ENDIAN)` line removed in https://github.com/ibus/ibus/pull/2477/commits/f733c18 :
`AC_MSG_RESULT()` just print a result of a check and won't affect a value itself.
https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Printing-Messages.html

If you meant 'the change' is to set/update `ENDIAN` value by
`ENDIAN="$ENDIAN ($ac_cv_c_bigendian, use ac_cv_c_bigendian to yes or no)" next to AC_SUBST(ENDIAN)`
line to print endianness description in `AC_MSG_RESULT` in `configure.ac`
https://github.com/ibus/ibus/blob/a4007f7d0bdfb98457487c85304188c411e6d991/configure.ac#L905
an actual value of  `$ENDIAN` is already set by
`AC_C_BIGENDIAN([ENDIAN=big],[ENDIAN=little],[ENDIAN=unknown],[])`
line and this new one will be overwritten the value.
I wonder what happens on reference of `$ENDIAN` in  and it's also referred in `src/Makefile.am`
https://github.com/ibus/ibus/blob/a4007f7d0bdfb98457487c85304188c411e6d991/src/Makefile.am#L271

2023-03-26 05:07 UTC, tsutsui commented
> Right, it helps me. I also will modify your patch if you're fine.

I can update commits to improve implementation details, but it's really hard to reflect design changes without written documents.
I don't mind you modify my patch (because my main subject is CI on NetBSD).

2023-03-27 11:12 UTC, fujiwarat commented on configure.ac
>  AC_SUBST(ENDIAN)
> an actual value of $ENDIAN is already set by AC_C_BIGENDIAN([ENDIAN=big],[ENDIAN=little],[ENDIAN=unknown],[]) line and this new one will be overwritten the value.

That's why I asked to update ENDIAN *after* AC_SUBST(ENDIAN)

```
 AC_SUBST(ENDIAN)
+ENDIAN="$ENDIAN ($ac_cv_c_bigendian, use ac_cv_c_bigendian to yes or no)"
```

2023-03-27 11:38 UTC, fujiwarat commented on configure.ac
>  AC_SUBST(ENDIAN)
Sorry, even if ENDIAN is updated after AC_SUBST(ENDIAN), the overriding ENDIAN reflects the Makefile recursively.

ENDIAN_MSG="$ENDIAN ($ac_cv_c_bigendian, use ac_cv_c_bigendian to yes or no)"

and
```
-  Build endianness              $ENDIAN
+  Build endianness              $ENDIAN_RESULT
```

2023-03-30 00:37 UTC, fujiwarat commented on configure.ac
>  AC_SUBST(ENDIAN)
Are you fine to update the configure result?

2023-03-30 17:05 UTC, tsutsui commented on configure.ac
>  AC_SUBST(ENDIAN)
> Are you fine to update the configure result?

No problem for me.

2023-04-05 05:56 UTC, closed without merging